sonar.projectKey=athlete-devops
sonar.projectName=Athlete DevOps System
sonar.sources=src
sonar.tests=tests
sonar.javascript.lcov.reportPaths=coverage/lcov.info
sonar.sourceEncoding=UTF-8
sonar.exclusions=node_modules/**,coverage/**
sonar.coverage.exclusions=tests/**